Description: 7777 Manual Setup

Parameters:
  Vpc:
    Type: AWS::EC2::VPC::Id
  SecurityGroupRds:
    Type: AWS::EC2::SecurityGroup::Id
  SecurityGroupElastiCache:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: EcsCluster
  BastionTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: port7777/server:1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: task
          Name: 7777-bastion
          PortMappings:
            - ContainerPort: 22
          Privileged: 'false'
      Cpu: 256
      Memory: 512
      Family: 7777-bastion
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt BastionTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt BastionTaskExecutionRole.Arn
      RequiresCompatibilities: [FARGATE]
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
  BastionTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ContainerSecurityGroupForVpc:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '7777-container-security-group-${Vpc}'
      GroupDescription: '[7777] Security Group for Fargate container'
      VpcId: !Ref Vpc
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  AuthorizeContainerSecurityGroupOnRds:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: '[7777] Authorize RDS Tunneling from Fargate Container'
      GroupId: !Ref SecurityGroupRds
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ContainerSecurityGroupForVpc
  AuthorizeContainerSecurityGroupOnElastiCache:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: '[7777] Authorize ElastiCache Tunneling from Fargate Container'
      GroupId: !Ref SecurityGroupElastiCache
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ContainerSecurityGroupForVpc
